// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "040fac46-c805-4eeb-9c37-3903b5f74555");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1701318862);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1701318982);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1701327725);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1701318622);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1701318155);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1701318742);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1701319222);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1701319102);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1701317967);
user_pref("browser.laterrun.bookkeeping.sessionCount", 7);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{de9fd4cc-541e-4340-b70a-5138243c2800}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1701291600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1701327704036");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1701329531036");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1701317972431");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1701339572431");
user_pref("browser.search.region", "KE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190128144255");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1701329739");
user_pref("browser.slowStartup.averageTime", 987);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190128144255");
user_pref("browser.startup.homepage_override.mstone", "65.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1701317970204");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "642ec813bf734693a8ad339546f94080");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1701318863);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190128144255");
user_pref("extensions.lastAppVersion", "65.0");
user_pref("extensions.lastPlatformVersion", "65.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"4b92cf8f-3397-4185-b41d-077ca5fe7c5f\",\"screenshots@mozilla.org\":\"327e8514-5ecc-44e6-aabb-b24d5bb2048f\",\"webcompat-reporter@mozilla.org\":\"dd7ec52d-acfa-414a-bb54-4d774c34c84c\",\"webcompat@mozilla.org\":\"614836e4-46b9-487e-beca-0bb31c6c94d9\",\"baidu-code-update@mozillaonline.com\":\"7ab1c066-337e-4e4b-98a3-fd18551e6daf\",\"fxmonitor@mozilla.org\":\"376f4e1c-30c4-406d-bac9-5c37e22df643\"}");
user_pref("idle.lastDailyNotification", 1701319996);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1701318081);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190128144255");
user_pref("media.gmp-manager.lastCheck", 1701318074);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1701319996);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "85a225d1-fe40-4560-ba09-ca178e306e5b");
user_pref("security.sandbox.plugin.tempDirSuffix", "403c7f15-8bf3-4883-bffe-2e0e3cc764ff");
user_pref("services.blocklist.addons.checked", 1701318748);
user_pref("services.blocklist.gfx.checked", 1701318748);
user_pref("services.blocklist.onecrl.checked", 1701318748);
user_pref("services.blocklist.plugins.checked", 1701318748);
user_pref("services.settings.clock_skew_seconds", 1);
user_pref("services.settings.last_update_seconds", 1701318748);
user_pref("services.settings.main.language-dictionaries.last_check", 1701318748);
user_pref("services.settings.main.sites-classification.last_check", 1701318748);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1701319996);
user_pref("toolkit.startup.last_success", 1701329737);
user_pref("toolkit.telemetry.cachedClientID", "d5c46d58-e6ed-489a-b2ca-0912e131b92d");
user_pref("toolkit.telemetry.previousBuildID", "20190128144255");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
